
services:
- type: web
  name: bluefield-siem
  env: python
  plan: free
  buildCommand: "pip install -r requirements.txt"
  startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
  envVars:
  - key: SECRET_KEY
    value: "yoursecretkeyhere"
  - key: ADMIN_USERNAME
    value: "admin"
  - key: ADMIN_PASSWORD
    value: "password"
